### ISSUE TITLE
ClassCastException

### ISSUE THREAD

**Issue by ayedo** [scalameter/scalameter#93]
Hi,

First of all: thanks for your awesome work!
I run a benchmark that gets stuck. When I abort it, the following is printed to the console:

```Scala
Error running separate JVM: java.lang.ClassCastException: cannot assign instance of scala.collection.immutable.HashMap$SerializationProxy to field org.scalameter.Context.properties of type scala.collection.immutable.Map in instance of org.scalameter.Context
```
What could the source of the problem be?

**Comment by axel22** [comment]
I believe that you are maybe using outputs from two different Scalameter versions.

There is a plan to add a new [persistor](https://github.com/scalameter/scalameter/blob/master/src/main/scala/org/scalameter/Persistor.scala) that is binary compatible across versions. This should be a simple task (just implement the `Persistor` interface, and make it a default), but I currently do not have the bandwidth. Pull requests are welcome.

**Comment by andrewdbate** [comment]
I can confirm that I am having the same issue.

My `built.sbt` is pretty simple:

```
resolvers += "Sonatype OSS Snapshots" at
  "https://oss.sonatype.org/content/repositories/releases"

libraryDependencies += "com.storm-enroute" %% "scalameter" % "0.6"

testFrameworks += new TestFramework("org.scalameter.ScalaMeterFramework")  

logBuffered := false

parallelExecution in Test := false

scalaVersion := "2.11.6"
```

The problem with the `ClassCastException` is currently happening even on the following example:

```scala
import org.scalameter.api._

object RangeBenchmark extends PerformanceTest {

  /* configuration */

  lazy val executor = SeparateJvmsExecutor(
    new Executor.Warmer.Default,
    Aggregator.min,
    new Measurer.Default)
  lazy val reporter = new LoggingReporter
  lazy val persistor = Persistor.None

  /* inputs */

  val sizes = Gen.range("size")(300000, 1500000, 300000)

  val ranges = for {
    size <- sizes
  } yield 0 until size

  /* tests */

  performance of "Range" in {
    measure method "map" in {
      using(ranges) in {
        r => r.map(_ + 1)
      }
    }
  }

}
```

I would be surprised if there is some problem with different Scalameter versions, since I have specified Scala 2.11.6 in my build script. I also tried with Scala 2.10, but still got the `ClassCastException`.

There are no other Scala files or dependencies in my example project.

The exception does not happen if `SeparateJvmsExecutor` is changed to `LocalExecutor`, but this is not what I need.

Is there a known workaround?

**Comment by axel22** [comment]
Please print the exact error message and the stack trace, so that we can provide better feedback.

Your error is probably due to the test snippet trying to serialize the entire test object when you're running in a separate JVM.
Since `SeparateJvmExecutor` is not serializable, you get the exception.

The solution is to declare your members using a `def` instead of a `val`, like this:

    def executor = new SeparateJvmExecutor(...)

**Comment by andrewdbate** [comment]
I changed all `val`s to `def`s, but still have the same error.

For completeness the modified example is:
```scala
import org.scalameter.api._

object RangeBenchmark extends PerformanceTest {

  /* configuration */

  def executor = SeparateJvmsExecutor(
    new Executor.Warmer.Default,
    Aggregator.min,
    new Measurer.Default)
  def reporter = new LoggingReporter
  def persistor = Persistor.None

  /* inputs */

  def sizes = Gen.range("size")(300000, 1500000, 300000)

  def ranges = for {
    size <- sizes
  } yield 0 until size

  /* tests */

  performance of "Range" in {
    measure method "map" in {
      using(ranges) in {
        r => r.map(_ + 1)
      }
    }
  }

}
```

The SBT build script is identical to that in my last comment.

The full exception is the following:
```
Test threw exception: java.lang.ClassCastException: cannot assign instance of scala.collection.immutable.HashMap$SerializationProxy to field org.scalameter.Context.properties of type scala.collection.immutable.Map in instance of o
rg.scalameter.Context
java.lang.ClassCastException: cannot assign instance of scala.collection.immutable.HashMap$SerializationProxy to field org.scalameter.Context.properties of type scala.collection.immutable.Map in instance of org.scalameter.Context
        at java.io.ObjectStreamClass$FieldReflector.setObjFieldValues(ObjectStreamClass.java:2089)
        at java.io.ObjectStreamClass.setObjFieldValues(ObjectStreamClass.java:1261)
        at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1999)
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1918)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
        at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1993)
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1918)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
        at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1993)
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1918)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:371)
        at org.scalameter.execution.JvmRunner.readOutput(JvmRunner.scala:45)
        at org.scalameter.execution.JvmRunner.run(JvmRunner.scala:18)
        at org.scalameter.execution.SeparateJvmsExecutor.sample$1(SeparateJvmsExecutor.scala:46)
        at org.scalameter.execution.SeparateJvmsExecutor.org$scalameter$execution$SeparateJvmsExecutor$$sampleReport$1(SeparateJvmsExecutor.scala:81)
        at org.scalameter.execution.SeparateJvmsExecutor$$anonfun$2.apply(SeparateJvmsExecutor.scala:95)
        at org.scalameter.execution.SeparateJvmsExecutor$$anonfun$2.apply(SeparateJvmsExecutor.scala:93)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
        at scala.collection.Iterator$class.foreach(Iterator.scala:750)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1202)
        at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
        at scala.collection.AbstractTraversable.map(Traversable.scala:104)
        at org.scalameter.execution.SeparateJvmsExecutor.runSetup(SeparateJvmsExecutor.scala:93)
        at org.scalameter.Executor$$anonfun$run$1.apply(Executor.scala:15)
        at org.scalameter.Executor$$anonfun$run$1.apply(Executor.scala:13)
        at org.scalameter.utils.Tree$$anonfun$1.apply(Tree.scala:17)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
        at scala.collection.immutable.List.map(List.scala:285)
        at org.scalameter.utils.Tree.map(Tree.scala:17)
        at org.scalameter.utils.Tree$$anonfun$2.apply(Tree.scala:18)
        at org.scalameter.utils.Tree$$anonfun$2.apply(Tree.scala:18)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
        at scala.collection.immutable.List.map(List.scala:285)
        at org.scalameter.utils.Tree.map(Tree.scala:18)
        at org.scalameter.utils.Tree$$anonfun$2.apply(Tree.scala:18)
        at org.scalameter.utils.Tree$$anonfun$2.apply(Tree.scala:18)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
        at scala.collection.immutable.List.map(List.scala:285)
        at org.scalameter.utils.Tree.map(Tree.scala:18)
        at org.scalameter.Executor$class.run(Executor.scala:13)
        at org.scalameter.execution.SeparateJvmsExecutor.run(SeparateJvmsExecutor.scala:19)
        at org.scalameter.PerformanceTest$Initialization$class.executeTests(PerformanceTest.scala:44)
        at org.scalameter.PerformanceTest.executeTests(PerformanceTest.scala:10)
        at org.scalameter.ScalaMeterFramework$$anon$1$$anonfun$run$1$$anonfun$apply$1$$anonfun$apply$2.apply(ScalaMeterFramework.scala:65)
        at org.scalameter.ScalaMeterFramework$$anon$1$$anonfun$run$1$$anonfun$apply$1$$anonfun$apply$2.apply(ScalaMeterFramework.scala:56)
        at org.scalameter.MonadicDynVar$$anon$1$$anonfun$foreach$1.apply(MonadicDynVar.scala:7)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
        at org.scalameter.MonadicDynVar$$anon$1.foreach(MonadicDynVar.scala:7)
        at org.scalameter.ScalaMeterFramework$$anon$1$$anonfun$run$1$$anonfun$apply$1.apply(ScalaMeterFramework.scala:56)
        at org.scalameter.ScalaMeterFramework$$anon$1$$anonfun$run$1$$anonfun$apply$1.apply(ScalaMeterFramework.scala:55)
        at org.scalameter.MonadicDynVar$$anon$1$$anonfun$foreach$1.apply(MonadicDynVar.scala:7)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
        at org.scalameter.MonadicDynVar$$anon$1.foreach(MonadicDynVar.scala:7)
        at org.scalameter.ScalaMeterFramework$$anon$1$$anonfun$run$1.apply(ScalaMeterFramework.scala:55)
        at org.scalameter.ScalaMeterFramework$$anon$1$$anonfun$run$1.apply(ScalaMeterFramework.scala:54)
        at org.scalameter.MonadicDynVar$$anon$1$$anonfun$foreach$1.apply(MonadicDynVar.scala:7)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
        at org.scalameter.MonadicDynVar$$anon$1.foreach(MonadicDynVar.scala:7)
        at org.scalameter.ScalaMeterFramework$$anon$1.run(ScalaMeterFramework.scala:54)
        at sbt.RunnerWrapper$1.runRunner2(FrameworkWrapper.java:223)
        at sbt.RunnerWrapper$1.execute(FrameworkWrapper.java:236)
        at sbt.TestRunner.runTest$1(TestFramework.scala:76)
        at sbt.TestRunner.run(TestFramework.scala:85)
        at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:202)
        at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:202)
        at sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:185)
        at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:202)
        at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:202)
        at sbt.TestFunction.apply(TestFramework.scala:207)
        at sbt.Tests$.sbt$Tests$$processRunnable$1(Tests.scala:239)
        at sbt.Tests$$anonfun$makeSerial$1.apply(Tests.scala:245)
        at sbt.Tests$$anonfun$makeSerial$1.apply(Tests.scala:245)
        at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
        at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:235)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

I am using Java 8 update 45.

**Comment by axel22** [comment]
Interesting - do you have this example online somewhere to try it out?

**Comment by andrewdbate** [comment]
I can upload this somewhere. Can you recommend the best way to do this? A mini GitHub project? Or something else?

**Comment by axel22** [comment]
I guess a GitHub project would be nice. Or you could just upload a zip with your sources, whatever is easier for you.

**Comment by andrewdbate** [comment]
For quickness I've put the files [here](http://1drv.ms/1LgELlM).

**Comment by axel22** [comment]
Thank you! I will dig into this now.

**Comment by axel22** [comment]
With:

    $ java -version
    java version "1.7.0_21"
    Java(TM) SE Runtime Environment (build 1.7.0_21-b11)
    Java HotSpot(TM) 64-Bit Server VM (build 23.21-b01, mixed mode)

Everything works for me:


    [info] size -> 1500000: 17.429, 17.406, 34.988, 17.503, 17.128, 17.131, 37.743, 17.457, 17.002, 17.244, 32.720, 17.636, 17.241, 17.484, 32.792, 17.709, 17.835, 17.177, 39.393, 17.758, 17.339, 16.949, 33.166, 17.574, 17.009, 17.024, 32.244, 17.478, 16.485, 16.792, 32.106, 17.375, 16.643, 16.857, 32.518, 17.114
    [info] ::Benchmark Range.map::
    [info] cores: 4
    [info] hostname: phoenix
    [info] jvm-name: Java HotSpot(TM) 64-Bit Server VM
    [info] jvm-vendor: Oracle Corporation
    [info] jvm-version: 23.21-b01
    [info] os-arch: amd64
    [info] os-name: Windows 7
    [info] Parameters(size -> 300000): 3.348301
    [info] Parameters(size -> 600000): 6.737738
    [info] Parameters(size -> 900000): 10.067791
    [info] Parameters(size -> 1200000): 13.516919
    [info] Parameters(size -> 1500000): 16.485421
    [info]
    [info] Passed: Total 0, Failed 0, Errors 0, Passed 0

**Comment by axel22** [comment]
I will try with Java 8.
Note that Scala 2.11 has only experimental support for Java 8.

**Comment by axel22** [comment]
I just tried this on

**Comment by axel22** [comment]
Btw, are you running this example through SBT?

**Comment by andrewdbate** [comment]
The classpath contains the following:
```
~/scala-meter-issue-93/target/scala-2.11/test-classes/
~/scala-meter-issue-93/target/scala-2.11/classes
~/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.11.6.jar
~/.ivy2/cache/com.storm-enroute/scalameter_2.11/jars/scalameter_2.11-0.6.jar
~/.ivy2/cache/com.storm-enroute/scalameter-core_2.11/jars/scalameter-core_2.11-0.6.jar
~/.ivy2/cache/org.apache.commons/commons-math3/jars/commons-math3-3.2.jar
~/.ivy2/cache/org.scala-lang/scala-reflect/jars/scala-reflect-2.11.0.jar
~/.ivy2/cache/org.scala-lang.modules/scala-xml_2.11/bundles/scala-xml_2.11-1.0.1.jar
~/.ivy2/cache/org.scala-lang.modules/scala-parser-combinators_2.11/bundles/scala-parser-combinators_2.11-1.0.1.jar
~/.ivy2/cache/com.github.wookietreiber/scala-chart_2.11/jars/scala-chart_2.11-0.4.2.jar
~/.ivy2/cache/org.jfree/jfreechart/jars/jfreechart-1.0.17.jar
~/.ivy2/cache/org.jfree/jcommon/jars/jcommon-1.0.21.jar
~/.ivy2/cache/xml-apis/xml-apis/jars/xml-apis-1.3.04.jar
~/.ivy2/cache/org.scala-lang.modules/scala-swing_2.11/bundles/scala-swing_2.11-1.0.1.jar
~/.ivy2/cache/org.scala-tools.testing/test-interface/jars/test-interface-0.5.jar
```

**Comment by andrewdbate** [comment]
And yes, I am running the example through SBT using the `test` command on the root project.

**Comment by axel22** [comment]
Could you run the same `println` command from within the `console` in SBT?

**Comment by andrewdbate** [comment]
When running the same `println` from `console` within SBT:

```
~/scala-meter-issue-93/target/scala-2.11/classes
~/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.11.6.jar
~/.ivy2/cache/com.storm-enroute/scalameter_2.11/jars/scalameter_2.11-0.6.jar
~/.ivy2/cache/com.storm-enroute/scalameter-core_2.11/jars/scalameter-core_2.11-0.6.jar
~/.ivy2/cache/org.apache.commons/commons-math3/jars/commons-math3-3.2.jar
~/.ivy2/cache/org.scala-lang/scala-reflect/jars/scala-reflect-2.11.0.jar
~/.ivy2/cache/org.scala-lang.modules/scala-xml_2.11/bundles/scala-xml_2.11-1.0.1.jar
~/.ivy2/cache/org.scala-lang.modules/scala-parser-combinators_2.11/bundles/scala-parser-combinators_2.11-1.0.1.jar
~/.ivy2/cache/com.github.wookietreiber/scala-chart_2.11/jars/scala-chart_2.11-0.4.2.jar
~/.ivy2/cache/org.jfree/jfreechart/jars/jfreechart-1.0.17.jar
~/.ivy2/cache/org.jfree/jcommon/jars/jcommon-1.0.21.jar
~/.ivy2/cache/xml-apis/xml-apis/jars/xml-apis-1.3.04.jar
~/.ivy2/cache/org.scala-lang.modules/scala-swing_2.11/bundles/scala-swing_2.11-1.0.1.jar
~/.ivy2/cache/org.scala-tools.testing/test-interface/jars/test-interface-0.5.jar
~/.ivy2/cache/org.scala-lang/scala-compiler/jars/scala-compiler-2.11.6.jar
~/.ivy2/cache/org.scala-lang/scala-reflect/jars/scala-reflect-2.11.6.jar
~/.ivy2/cache/org.scala-lang.modules/scala-xml_2.11/bundles/scala-xml_2.11-1.0.3.jar
~/.ivy2/cache/org.scala-lang.modules/scala-parser-combinators_2.11/bundles/scala-parser-combinators_2.11-1.0.3.jar
~/.ivy2/cache/jline/jline/jars/jline-2.12.1.jar
```

**Comment by axel22** [comment]
At the moment, I am unable to deduce what is causing this error.
It looks like it might be a classloader issue, where a classloader somehow cannot match a serialization proxy to a class that it has on the classpath, but can't tell for sure.

Could you try doing this in `build.sbt`:

    fork in test := true

**Comment by andrewdbate** [comment]
I think I've found the problem: It works on Linux, but it doesn't work on Windows. Everything I ran above was run on Windows 7 Enterprise x64. I just downloaded the zip that I linked to from this thread, compiled and ran the test on Fedora 20, and it worked just fine.

**Comment by axel22** [comment]
Might be the reason, still - I ran the with JDK7 on Windows 7, and with JDK8 on Ubuntu.
And `fork in test := true` in Windows did not change anything?

**Comment by andrewdbate** [comment]
I've just done that, adding `fork in test := true` on my Windows 7 machine with Java 8 update 45, and I get exactly the same exception as before.

**Comment by axel22** [comment]
I see. Unfortunately, I cannot say what is the problem.
A quick search on Google reveals a similar problem on the akka-user mailing list, and in [Apache Spark](https://github.com/dlwh/epic/issues/17). Discussions are, however, inconclusive.

**Comment by andrewdbate** [comment]
I'll try on another Windows machine later and report back if there is anything new.
Interestingly, the reporter of the issue you linked to claims to be using Java 7 update 51, which if true suggests that it is not a Java 7 vs 8 issue.

**Comment by andrewdbate** [comment]
I've just tried on another Windows machine (Windows 7 Professional x64 with Java 8 update 31) and I have exactly the same problem. If I find time, I'll try with Windows 7 and Java 7 this time.

**Comment by andrewdbate** [comment]
I can confirm that on a clean installation of Windows 7 Enterprise x64 with Java 8 update 45 (the latest available minor version of Java 8 as of writing), and running the same example, the exact same bug occurs.

**Comment by andrewdbate** [comment]
I now tried again, on yet another clean installation of Windows 7 Enterprise x64 with *Java 7 update 80* (the last available version of Java 7 at the time of writing), and I still get the same bug.
@axel22 You said that you tried on Windows 7 with Java 7. Which minor version did you use?

**Comment by axel22** [comment]
I used:

    java version "1.7.0_21"
    Java(TM) SE Runtime Environment (build 1.7.0_21-b11)
    Java HotSpot(TM) 64-Bit Server VM (build 23.21-b01, mixed mode)

I will try with a different Java version to check.

**Comment by andrewdbate** [comment]
I just tried on yet another clean installation of Windows 7 Enterprise x64 with Java 7 update 21, and I still get the same error as before.
```
$ java -version
java version "1.7.0_21"
Java(TM) SE Runtime Environment (build 1.7.0_21-b11)
Java HotSpot(TM) 64-Bit Server VM (build 23.21-b01, mixed mode)
```

**Comment by andrewdbate** [comment]
Just to be absolutely clear about the tests that I ran: I used a clean installation of Windows 7 Enterprise x64 with all updates installed inside virtual machine, with no other software installed, and then downloaded the particular version of the JDK from oracle.com and SBT 0.13.8 (using the Windows MSI version). I then downloaded the zip file that I linked from this thread and ran `sbt` from the root directory of the SBT project to launch the REPL. I then ran `test:compile` (which always completed successfully) and then `test` (which lead to the error in each case).

**Comment by axel22** [comment]
I see. For a moment there I thought that SBT 0.13.8 is the issue, but I think I know what your problem is.

It seems like you might be running a different Java version for SBT and for the separate JVM that ScalaMeter starts. This could happen if the `java.exe` is not available in your `PATH` variable. I was able to reproduce your problem by:

1. running (in Cygwin):

    $ which java
    /cygdrive/c/Program Files/Java/jdk1.7.0_21/bin/java

2. renaming `c:/Program Files/Java/jdk1.7.0_21/bin/java.exe` to `c:/Program Files/Java/jdk1.7.0_21/bin/java1.exe`.

4. In Cygwin:

    $ which java
    /cygdrive/c/Windows/system32/java

4. running SBT:

    $ sbt

5. In SBT:

    > test
    java.lang.ClassCastException: cannot assign instance of scala.collection.immutable.HashMap$SerializationProxy to field org.scalameter.Context.properties of type scala.collection.immutable.Map in instance of org.scalameter.Context

Renaming my `java1.exe` back to `java.exe` seems to resolve the problem.
Can you confirm that this is what's causing the issue?

(btw, thanks for the persistence in helping to track this down)

**Comment by andrewdbate** [comment]
It doesn't seem to make any difference, although I did not try in cygwin, I tried in Command Prompt.

I modified the path as you suggested. In particular, before making any changes to the configuration used for my previous comments I had that:
```
$ echo %PATH%
C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\sbt\\bin
$ where java
C:\Windows\System32\java.exe
```
And then modifying the path:
```
$ echo %PATH%
C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\sbt\\bin;C:\Program Files\Java\jdk1.7.0_21\bin
```

In both cases, the error was exactly the same:
```
> test
[info] Running test set for Range.map, curve Test-0
[info] Starting 36 measurements across 9 independent JVM runs.
[info] Starting new JVM: java -server -verbose:gc -Xmx2048m -Xms2048m -XX:CompileThreshold=100 -cp /C:/Users/Andrew%20Bate/Downloads/scala-meter-issue
-93/target/scala-2.11/test-classes/;/C:/Users/Andrew%20Bate/Downloads/scala-meter-issue-93/target/scala-2.11/classes;/C:/Users/Andrew%20Bate/.ivy2/cac
he/org.scala-lang/scala-library/jars/scala-library-2.11.6.jar;/C:/Users/Andrew%20Bate/.ivy2/cache/com.storm-enroute/scalameter_2.11/jars/scalameter_2.
11-0.6.jar;/C:/Users/Andrew%20Bate/.ivy2/cache/com.storm-enroute/scalameter-core_2.11/jars/scalameter-core_2.11-0.6.jar;/C:/Users/Andrew%20Bate/.ivy2/
cache/org.apache.commons/commons-math3/jars/commons-math3-3.2.jar;/C:/Users/Andrew%20Bate/.ivy2/cache/org.scala-lang/scala-reflect/jars/scala-reflect-
2.11.0.jar;/C:/Users/Andrew%20Bate/.ivy2/cache/org.scala-lang.modules/scala-xml_2.11/bundles/scala-xml_2.11-1.0.1.jar;/C:/Users/Andrew%20Bate/.ivy2/ca
che/org.scala-lang.modules/scala-parser-combinators_2.11/bundles/scala-parser-combinators_2.11-1.0.1.jar;/C:/Users/Andrew%20Bate/.ivy2/cache/com.githu
b.wookietreiber/scala-chart_2.11/jars/scala-chart_2.11-0.4.2.jar;/C:/Users/Andrew%20Bate/.ivy2/cache/org.jfree/jfreechart/jars/jfreechart-1.0.17.jar;/
C:/Users/Andrew%20Bate/.ivy2/cache/org.jfree/jcommon/jars/jcommon-1.0.21.jar;/C:/Users/Andrew%20Bate/.ivy2/cache/xml-apis/xml-apis/jars/xml-apis-1.3.0
4.jar;/C:/Users/Andrew%20Bate/.ivy2/cache/org.scala-lang.modules/scala-swing_2.11/bundles/scala-swing_2.11-1.0.1.jar;/C:/Users/Andrew%20Bate/.ivy2/cac
he/org.scala-tools.testing/test-interface/jars/test-interface-0.5.jar org.scalameter.execution.Main C:\Users\ANDREW~1\AppData\Local\Temp\newjvm-178524
4181490853426-io
Error: Could not find or load main class org.scalameter.execution.Main
[error] Error running separate JVM: java.lang.ClassCastException: cannot assign instance of scala.collection.immutable.HashMap$SerializationProxy to f
ield org.scalameter.Context.properties of type scala.collection.immutable.Map in instance of org.scalameter.Context
[error] Classpath: C:\Program Files (x86)\sbt\bin\sbt-launch.jar
Test threw exception: java.lang.ClassCastException: cannot assign instance of scala.collection.immutable.HashMap$SerializationProxy to field org.scala
meter.Context.properties of type scala.collection.immutable.Map in instance of org.scalameter.Context
java.lang.ClassCastException: cannot assign instance of scala.collection.immutable.HashMap$SerializationProxy to field org.scalameter.Context.properti
es of type scala.collection.immutable.Map in instance of org.scalameter.Context
        at java.io.ObjectStreamClass$FieldReflector.setObjFieldValues(Unknown Source)
        at java.io.ObjectStreamClass.setObjFieldValues(Unknown Source)
        at java.io.ObjectInputStream.defaultReadFields(Unknown Source)
        at java.io.ObjectInputStream.readSerialData(Unknown Source)
        at java.io.ObjectInputStream.readOrdinaryObject(Unknown Source)
        at java.io.ObjectInputStream.readObject0(Unknown Source)
        at java.io.ObjectInputStream.defaultReadFields(Unknown Source)
        at java.io.ObjectInputStream.readSerialData(Unknown Source)
        at java.io.ObjectInputStream.readOrdinaryObject(Unknown Source)
        at java.io.ObjectInputStream.readObject0(Unknown Source)
        at java.io.ObjectInputStream.defaultReadFields(Unknown Source)
        at java.io.ObjectInputStream.readSerialData(Unknown Source)
        at java.io.ObjectInputStream.readOrdinaryObject(Unknown Source)
        at java.io.ObjectInputStream.readObject0(Unknown Source)
        at java.io.ObjectInputStream.readObject(Unknown Source)
        at org.scalameter.execution.JvmRunner.readOutput(JvmRunner.scala:45)
        at org.scalameter.execution.JvmRunner.run(JvmRunner.scala:18)
        at org.scalameter.execution.SeparateJvmsExecutor.sample$1(SeparateJvmsExecutor.scala:46)
        at org.scalameter.execution.SeparateJvmsExecutor.org$scalameter$execution$SeparateJvmsExecutor$$sampleReport$1(SeparateJvmsExecutor.scala:81)
        at org.scalameter.execution.SeparateJvmsExecutor$$anonfun$2.apply(SeparateJvmsExecutor.scala:95)
        at org.scalameter.execution.SeparateJvmsExecutor$$anonfun$2.apply(SeparateJvmsExecutor.scala:93)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
        at scala.collection.Iterator$class.foreach(Iterator.scala:750)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1202)
        at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
        at scala.collection.AbstractTraversable.map(Traversable.scala:104)
        at org.scalameter.execution.SeparateJvmsExecutor.runSetup(SeparateJvmsExecutor.scala:93)
        at org.scalameter.Executor$$anonfun$run$1.apply(Executor.scala:15)
        at org.scalameter.Executor$$anonfun$run$1.apply(Executor.scala:13)
        at org.scalameter.utils.Tree$$anonfun$1.apply(Tree.scala:17)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
        at scala.collection.immutable.List.map(List.scala:285)
        at org.scalameter.utils.Tree.map(Tree.scala:17)
        at org.scalameter.utils.Tree$$anonfun$2.apply(Tree.scala:18)
        at org.scalameter.utils.Tree$$anonfun$2.apply(Tree.scala:18)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
        at scala.collection.immutable.List.map(List.scala:285)
        at org.scalameter.utils.Tree.map(Tree.scala:18)
        at org.scalameter.utils.Tree$$anonfun$2.apply(Tree.scala:18)
        at org.scalameter.utils.Tree$$anonfun$2.apply(Tree.scala:18)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
        at scala.collection.immutable.List.map(List.scala:285)
        at org.scalameter.utils.Tree.map(Tree.scala:18)
        at org.scalameter.Executor$class.run(Executor.scala:13)
        at org.scalameter.execution.SeparateJvmsExecutor.run(SeparateJvmsExecutor.scala:19)
        at org.scalameter.PerformanceTest$Initialization$class.executeTests(PerformanceTest.scala:44)
        at org.scalameter.PerformanceTest.executeTests(PerformanceTest.scala:10)
        at org.scalameter.ScalaMeterFramework$$anon$1$$anonfun$run$1$$anonfun$apply$1$$anonfun$apply$2.apply(ScalaMeterFramework.scala:65)
        at org.scalameter.ScalaMeterFramework$$anon$1$$anonfun$run$1$$anonfun$apply$1$$anonfun$apply$2.apply(ScalaMeterFramework.scala:56)
        at org.scalameter.MonadicDynVar$$anon$1$$anonfun$foreach$1.apply(MonadicDynVar.scala:7)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
        at org.scalameter.MonadicDynVar$$anon$1.foreach(MonadicDynVar.scala:7)
        at org.scalameter.ScalaMeterFramework$$anon$1$$anonfun$run$1$$anonfun$apply$1.apply(ScalaMeterFramework.scala:56)
        at org.scalameter.ScalaMeterFramework$$anon$1$$anonfun$run$1$$anonfun$apply$1.apply(ScalaMeterFramework.scala:55)
        at org.scalameter.MonadicDynVar$$anon$1$$anonfun$foreach$1.apply(MonadicDynVar.scala:7)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
        at org.scalameter.MonadicDynVar$$anon$1.foreach(MonadicDynVar.scala:7)
        at org.scalameter.ScalaMeterFramework$$anon$1$$anonfun$run$1.apply(ScalaMeterFramework.scala:55)
        at org.scalameter.ScalaMeterFramework$$anon$1$$anonfun$run$1.apply(ScalaMeterFramework.scala:54)
        at org.scalameter.MonadicDynVar$$anon$1$$anonfun$foreach$1.apply(MonadicDynVar.scala:7)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
        at org.scalameter.MonadicDynVar$$anon$1.foreach(MonadicDynVar.scala:7)
        at org.scalameter.ScalaMeterFramework$$anon$1.run(ScalaMeterFramework.scala:54)
        at sbt.RunnerWrapper$1.runRunner2(FrameworkWrapper.java:223)
        at sbt.RunnerWrapper$1.execute(FrameworkWrapper.java:236)
        at sbt.TestRunner.runTest$1(TestFramework.scala:76)
        at sbt.TestRunner.run(TestFramework.scala:85)
        at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:202)
        at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:202)
        at sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:185)
        at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:202)
        at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:202)
        at sbt.TestFunction.apply(TestFramework.scala:207)
        at sbt.Tests$.sbt$Tests$$processRunnable$1(Tests.scala:239)
        at sbt.Tests$$anonfun$makeSerial$1.apply(Tests.scala:245)
        at sbt.Tests$$anonfun$makeSerial$1.apply(Tests.scala:245)
        at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
        at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:235)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask$Sync.innerRun(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask$Sync.innerRun(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
[trace] Stack trace suppressed: run last test:test for the full output.
[error] Could not run test RangeBenchmark: java.lang.ClassCastException: cannot assign instance of scala.collection.immutable.HashMap$SerializationPro
xy to field org.scalameter.Context.properties of type scala.collection.immutable.Map in instance of org.scalameter.Context
[error] Error: Total 0, Failed 0, Errors 0, Passed 0
[error] Error during tests:
[error]         RangeBenchmark
[error] (test:test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 1 s, completed Jun 24, 2015 10:58:51 PM
```

Perhaps the interesting line is:
```
Error: Could not find or load main class org.scalameter.execution.Main
```

Could it be the case that the spawned JVM has its classpath messed up?

**Comment by axel22** [comment]
Ah, it means that the other JVM never ran the program, so ScalaMeter is trying to deserialize the inputs for the other JVM again.

I missed that line. It seems that the only classpath it picked up was the sbt-launch.jar, which is probably the reason why the Main class for the spawned JVM wasn't found.

On June 25, 2015 12:10:16 AM GMT+02:00, Andrew D Bate <notifications@github.com> wrote:
>It doesn't seem to make any difference, although I did not try in
>cygwin, I tried in Command Prompt.
>
>I modified the path as you suggested. In particular, before making any
>changes to the configuration used for my previous comments I had that:
>```
>$ echo %PATH%
>C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program
>Files (x86)\sbt\\bin
>$ where java
>C:\Windows\System32\java.exe
>```
>And then modifying the path:
>```
>$ echo %PATH%
>C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program
>Files (x86)\sbt\\bin;C:\Program Files\Java\jdk1.7.0_21\bin
>```
>
>In both cases, the error was exactly the same:
>```
>> test
>[info] Running test set for Range.map, curve Test-0
>[info] Starting 36 measurements across 9 independent JVM runs.
>[info] Starting new JVM: java -server -verbose:gc -Xmx2048m -Xms2048m
>-XX:CompileThreshold=100 -cp
>/C:/Users/Andrew%20Bate/Downloads/scala-meter-issue
>-93/target/scala-2.11/test-classes/;/C:/Users/Andrew%20Bate/Downloads/scala-meter-issue-93/target/scala-2.11/classes;/C:/Users/Andrew%20Bate/.ivy2/cac
>he/org.scala-lang/scala-library/jars/scala-library-2.11.6.jar;/C:/Users/Andrew%20Bate/.ivy2/cache/com.storm-enroute/scalameter_2.11/jars/scalameter_2.
>11-0.6.jar;/C:/Users/Andrew%20Bate/.ivy2/cache/com.storm-enroute/scalameter-core_2.11/jars/scalameter-core_2.11-0.6.jar;/C:/Users/Andrew%20Bate/.ivy2/
>cache/org.apache.commons/commons-math3/jars/commons-math3-3.2.jar;/C:/Users/Andrew%20Bate/.ivy2/cache/org.scala-lang/scala-reflect/jars/scala-reflect-
>2.11.0.jar;/C:/Users/Andrew%20Bate/.ivy2/cache/org.scala-lang.modules/scala-xml_2.11/bundles/scala-xml_2.11-1.0.1.jar;/C:/Users/Andrew%20Bate/.ivy2/ca
>che/org.scala-lang.modules/scala-parser-combinators_2.11/bundles/scala-parser-combinators_2.11-1.0.1.jar;/C:/Users/Andrew%20Bate/.ivy2/cache/com.githu
>b.wookietreiber/scala-chart_2.11/jars/scala-chart_2.11-0.4.2.jar;/C:/Users/Andrew%20Bate/.ivy2/cache/org.jfree/jfreechart/jars/jfreechart-1.0.17.jar;/
>C:/Users/Andrew%20Bate/.ivy2/cache/org.jfree/jcommon/jars/jcommon-1.0.21.jar;/C:/Users/Andrew%20Bate/.ivy2/cache/xml-apis/xml-apis/jars/xml-apis-1.3.0
>4.jar;/C:/Users/Andrew%20Bate/.ivy2/cache/org.scala-lang.modules/scala-swing_2.11/bundles/scala-swing_2.11-1.0.1.jar;/C:/Users/Andrew%20Bate/.ivy2/cac
>he/org.scala-tools.testing/test-interface/jars/test-interface-0.5.jar
>org.scalameter.execution.Main
>C:\Users\ANDREW~1\AppData\Local\Temp\newjvm-178524
>4181490853426-io
>Error: Could not find or load main class org.scalameter.execution.Main
>[error] Error running separate JVM: java.lang.ClassCastException:
>cannot assign instance of
>scala.collection.immutable.HashMap$SerializationProxy to f
>ield org.scalameter.Context.properties of type
>scala.collection.immutable.Map in instance of org.scalameter.Context
>[error] Classpath: C:\Program Files (x86)\sbt\bin\sbt-launch.jar
>Test threw exception: java.lang.ClassCastException: cannot assign
>instance of scala.collection.immutable.HashMap$SerializationProxy to
>field org.scala
>meter.Context.properties of type scala.collection.immutable.Map in
>instance of org.scalameter.Context
>java.lang.ClassCastException: cannot assign instance of
>scala.collection.immutable.HashMap$SerializationProxy to field
>org.scalameter.Context.properti
>es of type scala.collection.immutable.Map in instance of
>org.scalameter.Context
>at java.io.ObjectStreamClass$FieldReflector.setObjFieldValues(Unknown
>Source)
>        at java.io.ObjectStreamClass.setObjFieldValues(Unknown Source)
>        at java.io.ObjectInputStream.defaultReadFields(Unknown Source)
>        at java.io.ObjectInputStream.readSerialData(Unknown Source)
>        at java.io.ObjectInputStream.readOrdinaryObject(Unknown Source)
>        at java.io.ObjectInputStream.readObject0(Unknown Source)
>        at java.io.ObjectInputStream.defaultReadFields(Unknown Source)
>        at java.io.ObjectInputStream.readSerialData(Unknown Source)
>        at java.io.ObjectInputStream.readOrdinaryObject(Unknown Source)
>        at java.io.ObjectInputStream.readObject0(Unknown Source)
>        at java.io.ObjectInputStream.defaultReadFields(Unknown Source)
>        at java.io.ObjectInputStream.readSerialData(Unknown Source)
>        at java.io.ObjectInputStream.readOrdinaryObject(Unknown Source)
>        at java.io.ObjectInputStream.readObject0(Unknown Source)
>        at java.io.ObjectInputStream.readObject(Unknown Source)
>   at org.scalameter.execution.JvmRunner.readOutput(JvmRunner.scala:45)
>        at org.scalameter.execution.JvmRunner.run(JvmRunner.scala:18)
>at
>org.scalameter.execution.SeparateJvmsExecutor.sample$1(SeparateJvmsExecutor.scala:46)
>at
>org.scalameter.execution.SeparateJvmsExecutor.org$scalameter$execution$SeparateJvmsExecutor$$sampleReport$1(SeparateJvmsExecutor.scala:81)
>at
>org.scalameter.execution.SeparateJvmsExecutor$$anonfun$2.apply(SeparateJvmsExecutor.scala:95)
>at
>org.scalameter.execution.SeparateJvmsExecutor$$anonfun$2.apply(SeparateJvmsExecutor.scala:93)
>at
>scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
>at
>scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
>        at scala.collection.Iterator$class.foreach(Iterator.scala:750)
>      at scala.collection.AbstractIterator.foreach(Iterator.scala:1202)
>  at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
>        at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
>at
>scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
>     at scala.collection.AbstractTraversable.map(Traversable.scala:104)
>at
>org.scalameter.execution.SeparateJvmsExecutor.runSetup(SeparateJvmsExecutor.scala:93)
>     at org.scalameter.Executor$$anonfun$run$1.apply(Executor.scala:15)
>     at org.scalameter.Executor$$anonfun$run$1.apply(Executor.scala:13)
>        at org.scalameter.utils.Tree$$anonfun$1.apply(Tree.scala:17)
>at
>scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
>at
>scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
>        at scala.collection.immutable.List.foreach(List.scala:381)
>at
>scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
>        at scala.collection.immutable.List.map(List.scala:285)
>        at org.scalameter.utils.Tree.map(Tree.scala:17)
>        at org.scalameter.utils.Tree$$anonfun$2.apply(Tree.scala:18)
>        at org.scalameter.utils.Tree$$anonfun$2.apply(Tree.scala:18)
>at
>scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
>at
>scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
>        at scala.collection.immutable.List.foreach(List.scala:381)
>at
>scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
>        at scala.collection.immutable.List.map(List.scala:285)
>        at org.scalameter.utils.Tree.map(Tree.scala:18)
>        at org.scalameter.utils.Tree$$anonfun$2.apply(Tree.scala:18)
>        at org.scalameter.utils.Tree$$anonfun$2.apply(Tree.scala:18)
>at
>scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
>at
>scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
>        at scala.collection.immutable.List.foreach(List.scala:381)
>at
>scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
>        at scala.collection.immutable.List.map(List.scala:285)
>        at org.scalameter.utils.Tree.map(Tree.scala:18)
>        at org.scalameter.Executor$class.run(Executor.scala:13)
>at
>org.scalameter.execution.SeparateJvmsExecutor.run(SeparateJvmsExecutor.scala:19)
>at
>org.scalameter.PerformanceTest$Initialization$class.executeTests(PerformanceTest.scala:44)
>at
>org.scalameter.PerformanceTest.executeTests(PerformanceTest.scala:10)
>at
>org.scalameter.ScalaMeterFramework$$anon$1$$anonfun$run$1$$anonfun$apply$1$$anonfun$apply$2.apply(ScalaMeterFramework.scala:65)
>at
>org.scalameter.ScalaMeterFramework$$anon$1$$anonfun$run$1$$anonfun$apply$1$$anonfun$apply$2.apply(ScalaMeterFramework.scala:56)
>at
>org.scalameter.MonadicDynVar$$anon$1$$anonfun$foreach$1.apply(MonadicDynVar.scala:7)
>      at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
> at org.scalameter.MonadicDynVar$$anon$1.foreach(MonadicDynVar.scala:7)
>at
>org.scalameter.ScalaMeterFramework$$anon$1$$anonfun$run$1$$anonfun$apply$1.apply(ScalaMeterFramework.scala:56)
>at
>org.scalameter.ScalaMeterFramework$$anon$1$$anonfun$run$1$$anonfun$apply$1.apply(ScalaMeterFramework.scala:55)
>at
>org.scalameter.MonadicDynVar$$anon$1$$anonfun$foreach$1.apply(MonadicDynVar.scala:7)
>      at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
> at org.scalameter.MonadicDynVar$$anon$1.foreach(MonadicDynVar.scala:7)
>at
>org.scalameter.ScalaMeterFramework$$anon$1$$anonfun$run$1.apply(ScalaMeterFramework.scala:55)
>at
>org.scalameter.ScalaMeterFramework$$anon$1$$anonfun$run$1.apply(ScalaMeterFramework.scala:54)
>at
>org.scalameter.MonadicDynVar$$anon$1$$anonfun$foreach$1.apply(MonadicDynVar.scala:7)
>      at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
> at org.scalameter.MonadicDynVar$$anon$1.foreach(MonadicDynVar.scala:7)
>at
>org.scalameter.ScalaMeterFramework$$anon$1.run(ScalaMeterFramework.scala:54)
>        at sbt.RunnerWrapper$1.runRunner2(FrameworkWrapper.java:223)
>        at sbt.RunnerWrapper$1.execute(FrameworkWrapper.java:236)
>        at sbt.TestRunner.runTest$1(TestFramework.scala:76)
>        at sbt.TestRunner.run(TestFramework.scala:85)
>at
>sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:202)
>at
>sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:202)
>at
>sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:185)
>at
>sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:202)
>at
>sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:202)
>        at sbt.TestFunction.apply(TestFramework.scala:207)
>        at sbt.Tests$.sbt$Tests$$processRunnable$1(Tests.scala:239)
>        at sbt.Tests$$anonfun$makeSerial$1.apply(Tests.scala:245)
>        at sbt.Tests$$anonfun$makeSerial$1.apply(Tests.scala:245)
>   at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
>   at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
>        at sbt.std.Transform$$anon$4.work(System.scala:63)
>at
>sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
>at
>sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
>        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
>        at sbt.Execute.work(Execute.scala:235)
>        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
>        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
>at
>sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
>      at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
>       at java.util.concurrent.FutureTask$Sync.innerRun(Unknown Source)
>        at java.util.concurrent.FutureTask.run(Unknown Source)
> at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
>       at java.util.concurrent.FutureTask$Sync.innerRun(Unknown Source)
>        at java.util.concurrent.FutureTask.run(Unknown Source)
>   at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
>  at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
>        at java.lang.Thread.run(Unknown Source)
>[trace] Stack trace suppressed: run last test:test for the full output.
>[error] Could not run test RangeBenchmark:
>java.lang.ClassCastException: cannot assign instance of
>scala.collection.immutable.HashMap$SerializationPro
>xy to field org.scalameter.Context.properties of type
>scala.collection.immutable.Map in instance of org.scalameter.Context
>[error] Error: Total 0, Failed 0, Errors 0, Passed 0
>[error] Error during tests:
>[error]         RangeBenchmark
>[error] (test:test) sbt.TestsFailedException: Tests unsuccessful
>[error] Total time: 1 s, completed Jun 24, 2015 10:58:51 PM
>```
>
>Perhaps the interesting line is:
>```
>Error: Could not find or load main class org.scalameter.execution.Main
>```
>
>Could it be the case that the spawned JVM has its classpath messed up?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/scalameter/scalameter/issues/93#issuecomment-115025677

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by andrewdbate** [comment]
I just tried in cygwin on the Windows 7 virtual machine with Java 8 update 45, and it still doesn't work. I get the same error as before, namely:
```
Error: Could not find or load main class org.scalameter.execution.Main
```
Is the classpath being specified correctly? Is the leading slash correct?

**Comment by axel22** [comment]
The `classpath` is not correctly specified. It looks like there is a leading slash in every classpath entry.

Could you try overriding the `Key.classpath` key in the config part of your test? You should set it to something like:

    utils.ClassPath.default.split(";").map(_.tail).mkString("", ";", "")

**Comment by andrewdbate** [comment]
How do I do this? I guess that I need to add the line
```
org.scalameter.utils.ClassPath.default.split(";").map(_.tail).mkString("", ";", "")
```
somewhere.... but where?

**Comment by axel22** [comment]
Sorry, I suggested this, and I thought it would work, but it doesn't:

    performance of "Range" config (
      org.scalameter.Key.classpath -> org.scalameter.utils.ClassPath.default.split(";").map(_.tail).mkString("", ";", "")
    ) in {
      measure method "map" in {
        using(ranges) in {
          r =>
          r.map(_ + 1)
        }
      }
    }

Instead, please try this. First, in the test file, name your package `org.scalameter`:

    package org.scalameter

Next, replace your test snippet (`performance` block) with the following:

    val ctx = org.scalameter.dyn.currentContext.value
    org.scalameter.dyn.currentContext.withValue(ctx +
      (org.scalameter.Key.classpath -> org.scalameter.utils.ClassPath.default.split(";").map(_.tail).mkString("", ";", ""))) {
      println("MODIFIED!!! " + org.scalameter.dyn.currentContext.value.goe(org.scalameter.Key.classpath, ""))
      performance of "Range" in {
        measure method "map" in {
          using(ranges) in {
            r =>
            r.map(_ + 1)
          }
        }
      }
    }

For me, this replaces the classpath in the test by killing the leading slash (`/`) in all classpath entries.
If for some reason your JVM is interpreting classpaths differently than mine, this should fix it.

**Comment by andrewdbate** [comment]
It still doesn't quite work, but I'm now in a position to debug what is going on.
@axel22 Two questions: (1) Does your Windows username have a space in it? (2) Can you post the info line beginning
```
[info] Starting new JVM: java -server -verbose:gc -Xmx2048m -Xms2048m ...
```
that shows the classpath passed as argument to the forked JVM, please?

**Comment by andrewdbate** [comment]
I think I've finally fixed it! The problem was not with the leading slash `/`, the problem was with the fact that my Windows username contained a space (as is pretty common on Windows), and hence my user profile directory in `C:\Users\` contained a space.

In my case, my home directory was `C:\Users\Andrew Bate\`, and this is what caused the problem. If the example is run for a user whose user name does not contain a space, then it works.

If you look at my comment from 2 days ago, you can see that the classpath has percent encoding of spaces, which is wrong:
```
[info] Starting new JVM: java -server -verbose:gc -Xmx2048m -Xms2048m -XX:CompileThreshold=100 -cp /C:/Users/Andrew%20Bate/Downloads/scala-meter-issue
-93/target/scala-2.11/test-classes/;/C:/Users/Andrew%20Bate/Downloads/scala-meter-issue-93/target/scala-2.11/classes;/C:/Users/Andrew%20Bate/.ivy2/cac
he/org.scala-lang/scala-library/jars/scala-library-2.11.6.jar;/C:/Users/Andrew%20Bate/.ivy2/cache/com.storm-enroute/scalameter_2.11/jars/scalameter_2.
11-0.6.jar;  
.......
```
Therefore, one hack that fixes the problem is to replace `%20` with a space in the classpath string, and to enclose the entire classpath in double quotes.

The full working example that implements this temporary workaround is the following:
```scala
package org.scalameter

import org.scalameter.api._

object RangeBenchmark extends PerformanceTest {

  /* configuration */

  override def executor = SeparateJvmsExecutor(
    new Executor.Warmer.Default,
    Aggregator.min,
    new Measurer.Default)
  override def reporter = new LoggingReporter
  override def persistor = Persistor.None

  /* inputs */

  def sizes = Gen.range("size")(300000, 1500000, 300000)

  def ranges = for {
    size <- sizes
  } yield 0 until size

  /* tests */

  val ctx = org.scalameter.dyn.currentContext.value
  org.scalameter.dyn.currentContext.withValue(ctx +
    (org.scalameter.Key.classpath -> org.scalameter.utils.ClassPath.default.split(";").mkString("\"", ";", "\"").replace("%20"," "))) {
    println("MODIFIED!!! " + org.scalameter.dyn.currentContext.value.goe(org.scalameter.Key.classpath, ""))
    performance of "Range" in {
      measure method "map" in {
        using(ranges) in {
          r =>
          r.map(_ + 1)
        }
      }
    }
  }

}
```

Hence the implementation as-is is not guaranteed to work on Windows machines when some directory on the classpath contains a space.

The proper fix would likely require that that the URIs on the classpath are URL decoded (i.e. they do not contain percent encoding of spaces, and possibly other things in cases I haven't thought of), and that the full classpath is passed using quotes.

For example
```scala
"\"" + java.net.URLDecoder.decode("C:/Users/Joe%20Bloggs/") + "\""
```
is likely to be more reliable than
```scala
"\"" + "C:/Users/Joe%20Bloggs/".replace("%20", " ") + "\""
```
since it covers other cases that might also arise.

Passing the classpath in quotes works in both Command Prompt and cygwin on Windows.

The double quotes should not be added around the classpath if the example is run on *nix.

Now that we know what needs to be fixed, would it be possible to fix the code? Many thanks.

**Comment by axel22** [comment]
Nice catch, and thanks for looking into this!
I can fix this today/tomorrow - the 0.7-SNAPSHOT will soon resolve this issue.

On June 26, 2015 6:19:49 PM GMT+02:00, Andrew D Bate <notifications@github.com> wrote:
>I think I've finally fixed it! The problem was not with the leading
>slash `/`, the problem was with the fact that my Windows username
>contained a space (as is pretty common on Windows), and hence my user
>profile directory in `C:\Users\` contained a space.
>
>In my case, my home directory was `C:\Users\Andrew Bate\`, and this is
>what caused the problem. If the example is run for a user whose user
>name does not contain a space, then it works.
>
>If you look at my comment from 2 days ago, you can see that the
>classpath has percent encoding of spaces, which is wrong:
>```
>[info] Starting new JVM: java -server -verbose:gc -Xmx2048m -Xms2048m
>-XX:CompileThreshold=100 -cp
>/C:/Users/Andrew%20Bate/Downloads/scala-meter-issue
>-93/target/scala-2.11/test-classes/;/C:/Users/Andrew%20Bate/Downloads/scala-meter-issue-93/target/scala-2.11/classes;/C:/Users/Andrew%20Bate/.ivy2/cac
>he/org.scala-lang/scala-library/jars/scala-library-2.11.6.jar;/C:/Users/Andrew%20Bate/.ivy2/cache/com.storm-enroute/scalameter_2.11/jars/scalameter_2.
>11-0.6.jar;  
>.......
>```
>Therefore, one hack that fixes the problem is to replace `%20` with a
>space in the classpath string, and to enclose the entire classpath in
>double quotes.
>
>The full working example that implements this temporary workaround is
>the following:
>```scala
>package org.scalameter
>
>import org.scalameter.api._
>
>object RangeBenchmark extends PerformanceTest {
>
>  /* configuration */
>
>  override def executor = SeparateJvmsExecutor(
>    new Executor.Warmer.Default,
>    Aggregator.min,
>    new Measurer.Default)
>  override def reporter = new LoggingReporter
>  override def persistor = Persistor.None
>
>  /* inputs */
>
>  def sizes = Gen.range("size")(300000, 1500000, 300000)
>
>  def ranges = for {
>    size <- sizes
>  } yield 0 until size
>
>  /* tests */
>
>  val ctx = org.scalameter.dyn.currentContext.value
>  org.scalameter.dyn.currentContext.withValue(ctx +
>(org.scalameter.Key.classpath ->
>org.scalameter.utils.ClassPath.default.split(";").mkString("\"", ";",
>"\"").replace("%20"," "))) {
>println("MODIFIED!!! " +
>org.scalameter.dyn.currentContext.value.goe(org.scalameter.Key.classpath,
>""))
>    performance of "Range" in {
>      measure method "map" in {
>        using(ranges) in {
>          r =>
>          r.map(_ + 1)
>        }
>      }
>    }
>  }
>
>}
>```
>
>Hence the implementation as-is is not guaranteed to work on Windows
>machines when some directory on the classpath contains a space.
>
>The proper fix would likely require that that the URIs on the classpath
>are URL decoded (i.e. they do not contain percent encoding of spaces,
>and possibly other things in cases I haven't thought of), and that the
>full classpath is passed using quotes.
>
>For example
>```scala
>"\"" + java.net.URLDecoder.decode("C:/Users/Joe%20Bloggs/") + "\""
>```
>is likely to be more reliable than
>```scala
>"\"" + "C:/Users/Joe%20Bloggs/".replace("%20", " ") + "\""
>```
>since it covers other cases that might also arise.
>
>Passing the classpath in quotes works in both Command Prompt and cygwin
>on Windows.
>
>The double quotes should not be added around the classpath if the
>example is run on *nix.
>
>Now that we know what needs to be fixed, would it be possible to fix
>the code? Many thanks.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/scalameter/scalameter/issues/93#issuecomment-115745064

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by axel22** [comment]
The commit above should fix the issue. Please try in some 15 minutes with the 0.7-SNAPSHOT to see if the issue persists.

**Comment by andrewdbate** [comment]
The above commit *not* fix the issue.

Running the same example as before, the classpath no longer has percent encoding of spaces *but* the entire classpath is not surrounded by quotes. The relevant extract of the error is the following:
```
[info] Starting new JVM: java -server -verbose:gc -Xmx2048m -Xms2048m -XX:CompileThreshold=100 -cp /C:/Users/Andrew Bate/Downloads/scala-meter-issue-9
3-again/target/scala-2.11/test-classes/;/C:/Users/Andrew Bate/Downloads/scala-meter-issue-93-again/target/scala-2.11/classes;/C:/Users/Andrew Bate/.iv
y2/cache/org.scala-lang/scala-library/jars/scala-library-2.11.6.jar;
...
[error] Error running separate JVM: java.lang.ClassCastException: cannot assign instance of scala.collection.immutable.HashMap$SerializationProxy to f
ield org.scalameter.Context.properties of type scala.collection.immutable.Map in instance of org.scalameter.Context
```

Would it possible to fix this? Many thanks again.

**Comment by axel22** [comment]
Yes, that was a hasty fix.
I will submit another patch.

On June 28, 2015 5:34:28 PM GMT+02:00, Andrew D Bate <notifications@github.com> wrote:
>The above commit *not* fix the issue.
>
>Running the same example as before, the classpath no longer has percent
>encoding of spaces *but* the entire classpath is not surrounded by
>quotes. The relevant extract of the error is the following:
>```
>[info] Starting new JVM: java -server -verbose:gc -Xmx2048m -Xms2048m
>-XX:CompileThreshold=100 -cp /C:/Users/Andrew
>Bate/Downloads/scala-meter-issue-9
>3-again/target/scala-2.11/test-classes/;/C:/Users/Andrew
>Bate/Downloads/scala-meter-issue-93-again/target/scala-2.11/classes;/C:/Users/Andrew
>Bate/.iv
>y2/cache/org.scala-lang/scala-library/jars/scala-library-2.11.6.jar;
>...
>[error] Error running separate JVM: java.lang.ClassCastException:
>cannot assign instance of
>scala.collection.immutable.HashMap$SerializationProxy to f
>ield org.scalameter.Context.properties of type
>scala.collection.immutable.Map in instance of org.scalameter.Context
>```
>
>Would it possible to fix this? Many thanks again.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/scalameter/scalameter/issues/93#issuecomment-116292731

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by axel22** [comment]
The classpath argument should now be emitted in quotes.

https://github.com/scalameter/scalameter/commit/49c19165f121f54935eabf81a34d5bcadfb8b0af

**Comment by andrewdbate** [comment]
Has the snapshot been published? It still doesn't seem to work for me.

**Comment by axel22** [comment]
Looks like the Travis build was silently skipping the publish step when tests fail, instead of failing the build.

https://travis-ci.org/scalameter/scalameter/jobs/68517487

That is fixed, and the failing test is temporarily disabled.

**Comment by andrewdbate** [comment]
I've tried it, and it does fix it on Windows (either cygwin or Command Prompt) in the case where the classpath contains a space.

However, **the last commit (49c1916) breaks everything** (irrespective of whether the classpath contains a space or not) on *nix. On *nix systems, the classpath should not be surrounded with double quotes. (I've tried it, and contrary to what some websites say, it just doesn't work.)

**Comment by axel22** [comment]
Good, now we know that the thing works on Windows.
I will send another patch today.

On June 29, 2015 2:49:19 AM GMT+02:00, Andrew D Bate <notifications@github.com> wrote:
>I've tried it, and it does fix it on Windows (either cygwin or Command
>Prompt) in the case where the classpath contains a space.
>
>However, **the last commit (49c1916) breaks everything** (irrespective
>of whether the classpath contains a space or not) on *nix. On *nix
>systems, the classpath should not be surrounded with double quotes.
>(I've tried it, and contrary to what some websites say, it just doesn't
>work.)
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/scalameter/scalameter/issues/93#issuecomment-116364060

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by axel22** [comment]
That's what I get for pushing commits on the train. Everything should be fixed now, and I re-enabled the previously disabled test.

**Comment by andrewdbate** [comment]
I've just tried the snapshot again, and it works on Linux again.

However, it still doesn't work on Windows. I've look though your commits, and it appears that `platformSpecificExtract` is not being called from anywhere. It looks as though `platformSpecificExtract` should have been called everywhere instead of `extract` but isn't? If so, perhaps `extract` should have been marked as `private[this]` in object `ClassPath` so that this couldn't happen.

**Comment by axel22** [comment]
I should give myself a facepalm or two.
It should be fixed in this CL: https://github.com/scalameter/scalameter/commit/bab568d100294421fab22571a63f785b1d7f1f64

Would be useful to have multi-platform tests in place.

**Comment by andrewdbate** [comment]
I've just tried with the latest snapshot (I believe -- it seems to have updated on `oss.sonatype.org`) on Windows and it still isn't working. I haven't investigated why yet. Have you tired it using a path with spaces from Windows?

**Comment by axel22** [comment]
I went to Windows, checked out a clean repo clone to a dir with spaces in its path. I can confirm that this is a fix for me on Windows:

https://github.com/scalameter/scalameter/commit/8f087efaceaa7497b8dc07d90b5844b87f412430

**Comment by andrewdbate** [comment]
I'll try again once it appears on Sonatype. Multi-platform tests are probably a must. Travis CI doesn't seem to accept Windows builds at this time. Is there an alternative to Travis which does (that perhaps could be used alongside Travis)?

**Comment by axel22** [comment]
Other than Jenkins with a vm, none that I'm aware off at the moment.

**Comment by andrewdbate** [comment]
It works! Many thanks.

I noticed during my testing, however, that spaces in the path are not supported on Linux. Should that be added to the todo list?

**Comment by axel22** [comment]
We will probably introduce a `ClassPath` class, that contains the classpath information in a platform-independent manner, and retrieves the actual string on-demand (I'm looking around if something similar already exists). At that point, we will fix Linux as well.

**Comment by axel22** [comment]
Whitespaces should work on Linux now too:

https://github.com/scalameter/scalameter/commit/6c0b1364f35601270c11caf4eec6688c7fff21d2

**Comment by andrewdbate** [comment]
Just tried this on Linux and it works for me!

**Comment by axel22** [comment]
Awesome, great to hear that!

**Comment by andrewdbate** [comment]
Follow up on our exchange about continuous integration on Windows: Have you tired [AppVeyor](http://www.appveyor.com/)? It is apparently free for open source projects. The SBT native packager project uses it for its Windows tests (see https://github.com/sbt/sbt-native-packager).

**Comment by axel22** [comment]
No, I was not aware of it -- awesome, thanks for pointing out!
[I've set up](https://github.com/scalameter/scalameter/blob/master/appveyor.yml) an AppVeyor build.
